import React from "react";
import * as styles from "./termsconditionmobile.module.css";

function TermsConditionMobile() {
    return (
            <div className="container terms">
                <div className="row">
                    <div className="col-lg-12">
                        <h2>Terms & Conditions</h2>
                        <p>This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only.</p>
                        <h3>1. Using the Services</h3>
                        <p>This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only.</p>
                        <p>This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only.</p>
                        <h3>2. Ownership</h3>
                        <p>This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only.</p>
                        <h3>3. Feedback</h3>
                        <p>This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only.</p>
                        <h3>4. Term and Termination</h3>
                        <p>This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only.</p>
                        <h3>5. Indemnification</h3>
                        <p>This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only.</p>
                        <h3>6. Disclaimer</h3>
                        <p>This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only.</p>
                        <h3>7. Corrections</h3>
                        <p>This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only.</p>
                        <h3>8. Injunctive Relief</h3>
                        <p>This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only.</p>
                        <h3>9. Procedure for Making Claims of Copyright Infringement</h3>
                        <p>This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only.</p>
                        <h3>10. Privacy Policy & Consents</h3>
                        <p>This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only.</p>
                        <h3>11. Miscellaneous</h3>
                        <p>This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only.</p>
                        <h3>12. Legal Notice for New Jersey Residents</h3>
                        <p>This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only.</p>
                    </div>
                </div>
            </div>



    )
}
export default TermsConditionMobile