import React from "react";
import * as styles from "./privacymobile.module.css";
function PrivacyPolicyMobile(){
    return(
<div className="container terms">
                <div className="row">
                    <div className="col-lg-12">
                        <h2>Privacy Policy</h2>
                        <p>This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only.</p>
                        <h3>Information Collected</h3>
                        <p>This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only.</p>
                        <p>This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only.</p>
                        <h3>Information Use</h3>
                        <p>This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only.</p>
                        <h3>Cookies</h3>
                        <p>This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only.</p>
                        <h3>Disclosing Information</h3>
                        <p>This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only.</p>
                        <h3>Changes to this Policy</h3>
                        <p>This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only.</p>
                        <h3>Contacting Us</h3>
                        <p>This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only, it will be replaced with the actual text later. This text is for sample purposes only.</p>
                    </div>
                </div>
            </div>
    )
}
export default PrivacyPolicyMobile